Repository LabyMod/ultralight-java, pull requests merged in 2021-02, with the labels that each got.

#37 Add basic Java 9 JPMS support
  example/lwjgl3-opengl/src/main/java/com/labymedia/ultralight/lwjgl3/opengl/listener/ExampleLoadListener.java
  example/lwjgl3-opengl/src/main/java/com/labymedia/ultralight/lwjgl3/opengl/support/ViewContextProvider.java
  ultralight-java-base/build.gradle
  ultralight-java-databind/build.gradle
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/Databind.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/DatabindConfiguration.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/DatabindJavascriptClass.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/DatabindJavascriptExplicitAPI.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/DatabindJavascriptMethodHandler.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/api/InjectJavascriptContext.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/api/JavaAPI.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/cache/JavascriptClassCache.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/cache/NaiveJavascriptClassCache.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/call/CallData.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/call/HeuristicMethodChooser.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/call/MethodChooser.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/context/ContextProvider.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/context/ContextProviderFactory.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/utils/FunctionalInterfaceBinder.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/utils/FunctionalInvocationHandler.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/utils/JavascriptConversionUtils.java
Labels: enhancement

#38 Fix wrong JS conversion for object parameter types
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/call/HeuristicMethodChooser.java
  ultralight-java-databind/src/main/java/com/labymedia/ultralight/databind/utils/JavascriptConversionUtils.java
Labels: bug, component: data bindings

#40 Add YourKit sponsor reference
  README.md
Labels: documentation
